<a href="https://colab.research.google.com/github/obeabi/Stats/blob/main/NonParametric_tests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pingouin

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pingouin
  Downloading pingouin-0.5.3-py3-none-any.whl (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.6/198.6 kB 7.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.22.4)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.10.1)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.5.3)
Requirement already satisfied: matplotlib>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from pingouin) (3.7.1)
Requirement already satisfied: seaborn>=0.11 in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.12.2)
Requirement already satisfied: statsmodels>=0.13 in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.13.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from pingouin) (1.2.2)
Collecting pandas-flavor>=0.2.0 (from pingouin)
  Downloading pandas_flavor-0.5.0-py3-none-any.whl (7.1 kB)
Collecting outdated (from pingouin)
  Downloading outdated-0.2.2-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from pingouin) (0.8.10)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.2->pingouin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0->pingouin) (2022.7.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.10/dist-packages (from pandas-flavor>=0.2.0->pingouin) (2022.12.0)
Requirement already satisfied: lazy-loader>=0.1 in /usr/local/lib/python3.10/dist-packages (from pandas-flavor>=0.2.0->pingouin) (0.2)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.13->pingouin) (0.5.3)
Requirement already satisfied: setuptools>=44 in /usr/local/lib/python3.10/dist-packages (from outdated->pingouin) (67.7.2)
Collecting littleutils (from outdated->pingouin)
  Downloading littleutils-0.2.2.tar.gz (6.6 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from outdated->pingouin) (2.27.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->pingouin) (3.1.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.2->statsmodels>=0.13->pingouin) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->outdated->pingouin) (3.4)
Building wheels for collected packages: littleutils
  Building wheel for littleutils (setup.py) ... done
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7029 sha256=47a230972d4556df4d55208a3f7d895b402b09a768a3b282082bc79ba1da98cb
  Stored in directory: /root/.cache/pip/wheels/3d/fe/b0/27a9892da57472e538c7452a721a9cf463cc03cf7379889266
Successfully built littleutils
Installing collected packages: littleutils, outdated, pandas-flavor, pingouin
Successfully installed littleutils-0.2.2 outdated-0.2.2 pandas-flavor-0.5.0 pingouin-0.5.3

In [2]:
# import librraies
import numpy as np
import pingouin as pg
import scipy
import pandas as pd

## Example 1

A new approach to prenatal care is proposed for pregnant women living in a rural community. The new program involves in-home visits during the course of pregnancy in addition to the usual or regularly scheduled visits. A pilot randomized trial with 15 pregnant women is designed to evaluate whether women who participate in the program deliver healthier babies than women receiving usual care. The outcome is the APGAR scoretext annotation indicator measured 5 minutes after birth. Recall that APGAR scores range from 0 to 10 with scores of 7 or higher considered normal (healthy), 4-6 low and 0-3 critically low. The data are shown below.

In [3]:
# data
df ={ 'usual_care':[8,7,6,2,5,8,7,3],
     'new_program':[9,9,7,8,10,9,6, np.nan]
}

df = pd.DataFrame(df)
df.head(10)

   usual_care  new_program
0           8          9.0
1           7          9.0
2           6          7.0
3           2          8.0
4           5         10.0
5           8          9.0
6           7          6.0
7           3          NaN

In [4]:
# pingouin library
pg.mwu(df['usual_care'], df['new_program'], alternative = 'two-sided')

     U-val alternative     p-val       RBC      CLES
MWU    8.5   two-sided  0.026095  0.696429  0.151786

In [5]:
# scipy library
scipy.stats.mannwhitneyu(np.array([8,7,6,2,5,8,7,3]), np.array([9,9,7,8,10,9,6]), use_continuity= True, alternative= 'two-sided')

MannwhitneyuResult(statistic=8.5, pvalue=0.026094807223038648)

since p_value is less than the significance level (i.e.0.05), we reject the null hypothesis which is that both populations are equal

## Example 2

A clinical trial is run to assess the effectiveness of a new anti-retroviral therapy for patients with HIV. Patients are randomized to receive a standard anti-retroviral therapy (usual care) or the new anti-retroviral therapy and are monitored for 3 months. The primary outcome is viral load which represents the number of HIV copies per milliliter of blood. A total of 30 participants are randomized and the data are shown below.

In [6]:
# data
df ={'standard theraphy' : [7500,8000,2000,550,1250,1000,2250,6800,3400,6300,9100,970,1040,670,400] ,
     'new theraphy' : [400,250,800,1400,8000,7400,1020,6000,920,1420,2700,4200,5200,4100,0.000001000]
    
}

df = pd.DataFrame(df)

df.head()

   standard theraphy  new theraphy
0               7500         400.0
1               8000         250.0
2               2000         800.0
3                550        1400.0
4               1250        8000.0

In [7]:
# pingouin library
pg.mwu(df['standard theraphy'], df['new theraphy'], alternative = 'two-sided')

     U-val alternative     p-val       RBC      CLES
MWU  125.0   two-sided  0.618591 -0.111111  0.555556

In [8]:
# scipy library
scipy.stats.mannwhitneyu(df['standard theraphy'].values, df['new theraphy'].values,use_continuity=True, alternative='two-sided')

MannwhitneyuResult(statistic=125.0, pvalue=0.6185914758545639)

since p_value is greater than the significance level (i.e.0.05), we fail to reject the null hypothesis which is that both populations are equal

# Tests with Matched Samples
## Wilcoxon Signed Rank Test

# Example One

Consider a clinical investigation to assess the effectiveness of a new drug designed to reduce repetitive behaviors in children affected with autism. If the drug is effective, children will exhibit fewer repetitive behaviors on treatment as compared to when they are untreated. A total of 8 children with autism enroll in the study. Each child is observed by the study psychologist for a period of 3 hours both before treatment and then again after taking the new drug for 1 week. The time that each child is engaged in repetitive behavior during each 3 hour observation period is measured. Repetitive behavior is scored on a scale of 0 to 100 and scores represent the percent of the observation time in which the child is engaged in repetitive behavior. For example, a score of 0 indicates that during the entire observation period the child did not engage in repetitive behavior while a score of 100 indicates that the child was constantly engaged in repetitive behavior. The data are shown below.

In [13]:
# data
df = { 'child': [ 1,2,3,4,5,6,7,8] ,
       ' before treatment': [85,70,40,65,80,75,55,20] ,
      'after one week treatment': [75,50,50,40,20,65,40,25]
    
}
# A nonparametric test is appropriate to test whether there is significant improvement in repetitive behavior before versus after treatment. The hypotheses are given below.

#H0: The median difference is zero  versus
#H1: The median difference is positive α=0.05

df = pd.DataFrame(df)
df.set_index('child', inplace = True)
df.head()

        before treatment  after one week treatment
child
1                     85                        75
2                     70                        50
3                     40                        50
4                     65                        40
5                     80                        20

H0: The median difference is zero  versus

H1: The median difference is positive α=0.05

In [16]:
# pingoiun library
pg.wilcoxon(df[' before treatment'], df['after one week treatment'], alternative='greater')

          W-val alternative     p-val       RBC      CLES
Wilcoxon   32.0     greater  0.027344  0.777778  0.726562

In [17]:
# scipy library
from scipy.stats import wilcoxon
wilcoxon(df[' before treatment'], df['after one week treatment'], alternative='greater')

WilcoxonResult(statistic=32.0, pvalue=0.02734375)

Because the p-value = 0.027 does not exceed the level of significance (α=0.05) we  have statistically significant evidence at α =0.05 to show that there is an improvement  after treatment as compared to before.

## Example 2

A study is run to evaluate the effectiveness of an exercise program in reducing systolic blood pressure in patients with pre-hypertension (defined as a systolic blood pressure between 120-139 mmHg or a diastolic blood pressure between 80-89 mmHg). A total of 15 patients with pre-hypertension enroll in the study, and their systolic blood pressures are measured. Each patient then participates in an exercise training program where they learn proper techniques and execution of a series of exercises. Patients are instructed to do the exercise program 3 times per week for 6 weeks. After 6 weeks, systolic blood pressures are again measured. The data are shown below

In [11]:
# data
df = { 'patient' : [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],
      
      'before treatment':[125,132,138,120,125,127,136,139,131,132,135,136,128,127,130],
      'after treatment': [118,134,130,124,105,130,130,132,123,128,126,140,135,126,132]
    
}

# The question of interest is whether there is a difference in QOL after chemotherapy treatment as compared to before. 
df = pd.DataFrame(df)
df.set_index('patient', inplace = True) 
df.head()

         before treatment  after treatment
patient
1                     125              118
2                     132              134
3                     138              130
4                     120              124
5                     125              105

In [12]:
# pingouin library
pg.wilcoxon(df['before treatment'], df['after treatment'], alternative = 'two-sided')

          W-val alternative     p-val       RBC      CLES
Wilcoxon   31.0   two-sided  0.106995  0.483333  0.615556

We do not reject H0 because p_vlaue > 0.05. Therefore, we do not have statistically significant evidence at α=0.05, to show that the median difference in systolic blood pressures is not zero (i.e., that there is a significant difference in systolic blood pressures after the exercise program as compared to before).

## Tests with More than Two Independent Samples

## Example 1
A clinical study is designed to assess differences in albumin levels in adults following diets with different amounts of protein. Low protein diets are often prescribed for patients with kidney failure. Albumin is the most abundant protein in blood, and its concentration in the serum is measured in grams per deciliter (g/dL). Clinically, serum albumin concentrations are also used to assess whether patients get sufficient protein in their diets. Three diets are compared, ranging from 5% to 15% protein, and the 15% protein diet represents a typical American diet. The albumin levels of participants following each diet are shown below. Is there is a difference in serum albumin levels among subjects on the three different diets?

In [20]:
# scipy library
#Set up hypotheses and determine level of significance.
#H0: The three population medians are equal versus
#H1: The three population medians are not all equal α=0.05
five_percent_protien=[3.1,2.6,2.9]
ten_percent_protien = [3.8,4.1,2.9,3.4,4.2] 
fifteen_percent_protien= [4.0, 5.5,5.0,4.8]
# perform krusal wallis test
from scipy.stats import kruskal
kruskal(five_percent_protien, ten_percent_protien, fifteen_percent_protien, nan_policy='propagate')

KruskalResult(statistic=7.549473684210525, pvalue=0.02294312751270393)

We  reject H0 because p_vlaue < 0.05. Therefore, we  have statistically significant evidence at α=0.05, to show that the median serum albumin levels amongst the diets is different.

## Example 2

A personal trainer is interested in comparing the anaerobic thresholds of elite athletes. Anaerobic threshold is defined as the point at which the muscles cannot get more oxygen to sustain activity or the upper limit of aerobic exercise. It is a measure also related to maximum heart rate. The following data are anaerobic thresholds for distance runners, distance cyclists, distance swimmers and cross-country skiers.  

 Is a difference in anaerobic thresholds among the different groups of elite athletes?

In [21]:
# pingouinlibrary
data = { ' distance runners': [185,179,192,165,174],
         'distance cyclists' :[190,209,182,178,181],
        'distance swimmers':[166,159,170, 183,160],
        'cross country skiers': [201,195,180,187,216]
}

df = pd.DataFrame(data)
df.head()

,distance runners,distance cyclists,distance swimmers,cross country skiers
0,185,190,166,201
1,179,209,159,195
2,192,182,170,180
3,165,178,183,187
4,174,181,160,216

In [23]:
#Set up hypotheses and determine level of significance.
#H0: The four population medians are equal versus
#H1: The four population medians are not all equal α=0.05

# perform krusal wallis test
from scipy.stats import kruskal
kruskal(df[' distance runners'], df['distance cyclists'], df['distance swimmers'],df['cross country skiers'], nan_policy='propagate')

KruskalResult(statistic=9.114285714285714, pvalue=0.027809360261068908)

e have statistically significant evidence at α =0.05, to show that there is a difference in median anaerobic thresholds among the four different groups of elite athletes.